name: Bug Report
description: Report a bug or unexpected behavior in TCAdmin V3
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the information below to help us investigate quickly.

        - Check the docs first: https://docs.tcadmin.com
        - If this is a feature request, post it in Discussions: https://github.com/TotalControlAdmin/TCAdmin-V3-Issues-and-Feedback/discussions
        Providing a minimal reproduction, logs and the exact TCAdmin version greatly speeds up triage.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal, exact steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages / stack traces).
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: TCAdmin Version
      description: Which version of TCAdmin V3 are you running?
      placeholder: e.g. 3.0.0-beta
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Component / Area
      description: Which part of TCAdmin is affected?
      options:
        - Web Interface
        - API
        - Installer
        - Agent
        - Database
        - Authentication
        - CLI
        - Docker
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows Server 2022
        - Windows Server 2019
        - Windows Server 2016
        - Ubuntu 24.04
        - Ubuntu 22.04
        - Debian 12
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Production
        - Staging
        - Development / Local
        - Test / CI
        - Other

  - type: dropdown
    id: frequency
    attributes:
      label: How often does this occur?
      options:
        - Always
        - Sometimes
        - Intermittent
        - Once
        - Unknown
    validations:
      required: true

  - type: input
    id: regression
    attributes:
      label: Regression (optional)
      description: Did this used to work in a previous version? If yes, which version?
      placeholder: e.g. Worked in 3.0.1

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output here (surrounding lines help). Use code blocks or attach log files.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Attachments
      description: Attach screenshots, recordings or configuration snippets. Images/files can be uploaded after creating the issue.

  - type: dropdown
    id: impact
    attributes:
      label: Impact / Severity (optional)
      options:
        - Blocker
        - High
        - Medium
        - Low
        - Trivial

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate.
          required: true
